# Generated by Django 4.2 on 2023-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenia',
            name='contenido',
            field=models.TextField(max_length=10000, verbose_name='Content'),
        ),
    ]
